version: '3'

services:
  simulator:
    build: 
      context: .
      dockerfile: dockerfile
    image: 5g-handover-sim:latest
    working_dir: /app
    command: bash
    tty: true
    stdin_open: true
    volumes:
      - ./handover-simulator/src:/app/handover-simulator/src